version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysqlnode
    environment:
      MYSQL_ROOT_PASSWORD: oktay
      MYSQL_DATABASE: stage
      MYSQL_PASSWORD: oktay
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminnode
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: oktay
    ports:
      - "8181:80"

volumes:
  db_data:
